### ISSUE TITLE
Leaked Cloudflare Token

### ISSUE THREAD

**Issue by wdhdev** [is-not-tech/register#13]
You guys have leaked your Cloudflare API token in your creds.json file. 

https://github.com/is-not-tech/register/blob/main/creds.json

(also FYI, you do not need to create a creds.json file on the repo if you are using Open Domains' CI, the workflow does it automatically)

**Comment by TrivCodez** [comment]
Hello!
Thanks for commenting, we are completely aware however we are having some issues with DNS Control, and this was the only way to fix it.. If something happens, then I would reroll the api key with OLD records and then re-add them via the git repo!
Thanks again!

**Comment by TrivCodez** [comment]
**Yeah I tried my best reproducing the issue and it did not work.**

> Will be re-trying after my exam period ..
